Mise en place des entitées ainsi que des fixtures pour users, offers,…
Nouvelle-Techno-fr/JeBenevole.fr pull request #33
Opened 2021-08-17 13:49 UTC by Nox5

… category, associations

2021-08-17 14:52 UTC, gallarian commented
pour une première version, c'est pas mal.
1) dommage qu'il y ai pas les relations misent dans les fixtures, genre une association associé a un user de maniere aléatoire
2) Code inspector invalide le check car il vous demande que vos fichiers ne depassent pas 45 methodes et attributs, peut etre essayé de trouver une possibilité a sa.

2021-08-17 18:27 UTC, NouvelleTechno requested changes

2021-08-17 18:27 UTC, NouvelleTechno commented on src/Entity/Offers.php
> +    private $zip;
Zip est un type string

2021-08-17 18:27 UTC, NouvelleTechno commented on src/Entity/Users.php
> +    private $fixNumber;
Comment est stocké un numéro de type +33612345678 ?

2021-08-17 18:31 UTC, gallarian approved these changes

2021-08-20 17:00 UTC, NouvelleTechno requested changes

2021-08-20 17:00 UTC, NouvelleTechno commented on src/Entity/Offers.php
> +    private $zip;
255 c'est un peu long pour un code postal

2021-08-20 17:00 UTC, NouvelleTechno commented on src/Entity/Offers.php
>      }
Le setter (setZip) n'est pas à jour

2021-08-20 17:00 UTC, NouvelleTechno commented on src/Entity/Users.php
> +    private $fixNumber;
12 c'est limite, en général on met entre 15 et 20

2021-08-20 18:31 UTC, gallarian commented on src/Entity/Offers.php
> +     * @ORM\Column(type="string", length=5)
pour rappel y pas que la France qui parle le francais et ses pays ont des codes postaux plus pour certains

2021-08-20 18:51 UTC, NouvelleTechno requested changes
Voir commentaire de Gallarian

2021-08-21 13:09 UTC, NouvelleTechno approved these changes

2021-08-21 13:09 UTC, merged