Crud association
Nouvelle-Techno-fr/JeBenevole.fr pull request #45
Opened 2021-08-28 15:10 UTC by J7DevWeb

CRUD-ASSOCIATIONS--------
ignore .htaccess in gitignore file.
AssociationController and AssociationType added.
AssociationController contain 5 routes : create, edit, delete, list and show.
4 templates added to test create, edit, list and show routes (routes list updated on excel).
Folders image/associationPictures are not pushed (but automatically created when needed).
Slug is not editable on edit route.
Slug = association name.
When an association is delete data are anonymized.
Association picture is deleted from picture folder when association is updated with a new picture.
Association pictures are not deleted when an association is deleted.

Fixtures---------------
AssociationFixtures updated on Email field to respect constaints.
CategoriesFixtures on line 27($categories->setParentId(1)) because this method do not exist in entity. I comment it for now.
Offersfixtures bug on line 43 the fixture do not respect database length constraint so insertion fail. Correction have been made.

Marks-----------------
Association name are not unique. We maybe need to update that.

ToDo------------------
Association are not related to user. We will need to update that.
buttons are not yet translated on forms create and edit.
Data are anonymized when we hit delete route but it will need to be adapted.

close#27

2021-08-28 15:30 UTC, NouvelleTechno requested changes

2021-08-28 15:30 UTC, NouvelleTechno commented on .gitignore
> +/public/.htaccess
Pourquoi mettre le .htaccess dans gitignore ?

2021-08-28 15:30 UTC, NouvelleTechno commented on config/services.yaml
> +    association_images_directory: '%kernel.project_dir%/public/images/associationPictures'
/public/images/associations serait plus adapté, pas besoin de rappeler "pictures"

2021-08-28 15:30 UTC, NouvelleTechno commented on src/Controller/AssociationController.php
> +     * @Route("/association/creation", name="new_association")
/associations/creation stp, toutes les routes au pluriel

2021-08-28 15:30 UTC, NouvelleTechno commented on src/Controller/AssociationController.php
> +    public function edit(Request $request, Associations $association, string $slug, EntityManagerInterface $em, AssociationService $assoService): Response
Pourquoi ne pas profiter du paramConverter pour récupérer l'association ? (idem pour les autres méthodes plus bas), ou alors retirer $slug des paramètres

2021-08-28 15:30 UTC, NouvelleTechno commented on src/Form/AssociationType.php
> +                        'mimeTypesMessage' => 'Image non valide. Probléme de format ou de taille.',
problème pas probléme

2021-08-28 15:30 UTC, NouvelleTechno commented on src/Service/AssociationService.php
> +        if ($image) {
Pourquoi vérifier si on a une image ?

2021-08-28 15:30 UTC, NouvelleTechno commented on src/Service/AssociationService.php
> +    public function uploadImage($image, $association)
Il faudrait types les paramètres

2021-08-28 15:30 UTC, NouvelleTechno commented on src/Service/AssociationService.php
> +            unlink($this->params->get('association_images_directory'). '/' .$image);
Il faut vérifier si le fichier existe avant unlink

2021-08-28 15:30 UTC, NouvelleTechno commented on templates/association/create.html.twig
> +{% block title %}Hello AssociationController!{% endblock %}
Penser à modifier le titre

2021-08-28 15:30 UTC, NouvelleTechno commented on templates/association/edit.html.twig
> +{% block title %}Hello AssociationController!{% endblock %}
Penser à modifier le titre

2021-08-28 15:30 UTC, NouvelleTechno commented on templates/association/list.html.twig
> +{% block title %}Hello AssociationController!{% endblock %}
Penser à modifier le titre

2021-08-28 15:48 UTC, gallarian commented on .gitignore
> +/public/.htaccess
why add the .htaccess in the dev phase, we don't need it

2021-08-28 15:48 UTC, gallarian commented on config/services.yaml
> +    association_images_directory: '%kernel.project_dir%/public/images/associationPictures'
the name is redundant, we are already in an image folder, Picture is useless

2021-08-28 15:48 UTC, gallarian commented on src/DataFixtures/CategoriesFixtures.php
> +            //$categories->setParentId(1);
why have you commented on this line, it is necessary or a category will have sub-categories

2021-08-28 15:48 UTC, gallarian commented on src/Form/AssociationType.php
> +                'required' => true,
instruction useless given that in the entity the properties cannot be null, the same for all the other fields having this instruction

2021-08-28 15:48 UTC, gallarian commented on src/Form/AssociationType.php
> +                ])
lack of verification, how to know that the url entered by the user is a Facebook address, the same for the other fields

2021-08-28 15:48 UTC, gallarian commented on src/Repository/AssociationsRepository.php
>      }
currently useless method for what fact, a findBy would have been good

2021-08-28 15:48 UTC, gallarian commented on src/Service/AssociationService.php
> +    }
this is not an upload service, a service is intended to be reused which is not the case with this method and in addition very heavy for what it has to do

2021-08-28 15:48 UTC, gallarian commented on templates/association/create.html.twig
> +{% endblock %}
redundant code compared to edit.html.twig, the only things that change are the h1 and the textual content of the submit button

2021-08-28 15:48 UTC, gallarian commented on templates/association/list.html.twig
> +{% endblock %}
html structure a little weak for a display of a web page

2021-08-28 15:49 UTC, gallarian commented
a PR is not a todolist, so the todo part has nothing to do here but rather in an issue

2021-08-28 16:39 UTC, J7DevWeb commented on .gitignore
> +/public/.htaccess
I need it to make my routes work on dev phase. Without it i got error.

2021-08-28 16:57 UTC, J7DevWeb commented on src/DataFixtures/CategoriesFixtures.php
> +            //$categories->setParentId(1);
Oops. That's an error. I will change that immediatly.

2021-08-28 17:09 UTC, J7DevWeb commented on src/Form/AssociationType.php
> +                'required' => true,
I'am not sure to understand. Are you referring to the option "required"?

2021-08-28 17:13 UTC, J7DevWeb commented on src/Service/AssociationService.php
> +        if ($image) {
Effectivement ce n'est pas nécessaire. Je modifie le code.

2021-08-28 17:19 UTC, J7DevWeb commented on src/Service/AssociationService.php
> +            unlink($this->params->get('association_images_directory'). '/' .$image);
Je le fais dans le AssociationController en vérifiant si un nom d'image est enregistrer avant de gérer la requête du formulaire.

2021-08-28 17:22 UTC, J7DevWeb commented on src/Service/AssociationService.php
> +    }
So it's better if for now I do all the logical in the AssociationController? Maybe a private function at the end of the file to avoid repetitions?

2021-08-28 18:11 UTC, gallarian commented on .gitignore
> +/public/.htaccess
if you don't have the symfony binary, you can use the internal php server

now as Benoit says why put it in the .gitignore? it won't be a concern for others, so it's a choice to make

2021-08-28 18:11 UTC, gallarian commented on src/Form/AssociationType.php
> +                'required' => true,
yes

2021-08-28 18:12 UTC, gallarian commented on src/Service/AssociationService.php
> +    }
no at all, except that you have made a semblance of service but which does not meet the criterion of a service

2021-08-30 08:27 UTC, J7DevWeb commented on src/Form/AssociationType.php
> +                ])
corrections made

2021-08-30 08:28 UTC, J7DevWeb commented on src/Form/AssociationType.php
> +                'required' => true,
corrections made

2021-08-30 08:29 UTC, J7DevWeb commented on config/services.yaml
> +    association_images_directory: '%kernel.project_dir%/public/images/associationPictures'
corrections made. (/public/images/associations)

2021-08-30 08:30 UTC, J7DevWeb commented on .gitignore
> +/public/.htaccess
Same problem with internal php server. I remove htaccess from gitignore.

2021-08-30 08:31 UTC, J7DevWeb commented on src/Service/AssociationService.php
> +    public function uploadImage($image, $association)
Correction apportée.

2021-08-30 08:31 UTC, J7DevWeb commented on src/Controller/AssociationController.php
> +     * @Route("/association/creation", name="new_association")
Correction apportée.

2021-08-30 08:32 UTC, J7DevWeb commented on config/services.yaml
> +    association_images_directory: '%kernel.project_dir%/public/images/associationPictures'
Modification faite.

2021-08-30 08:48 UTC, J7DevWeb commented on templates/association/list.html.twig
> +{% endblock %}
Corrections made.

2021-08-30 08:49 UTC, J7DevWeb commented on templates/association/create.html.twig
> +{% endblock %}
Ok so I grouped them together in one template.

2021-08-30 08:50 UTC, J7DevWeb commented on templates/association/create.html.twig
> +{% block title %}Hello AssociationController!{% endblock %}
Fait.

2021-08-30 09:41 UTC, NouvelleTechno requested changes

2021-08-30 09:41 UTC, NouvelleTechno commented on src/Service/AssociationService.php
> +    public function uploadImage(object $image, Associations $association)
C'est un object qu'attend la méthode move ?

2021-08-30 09:41 UTC, NouvelleTechno commented on templates/association/list.html.twig
> +        {{ association.email }}
Pas de balises HTML ?

2021-08-30 10:41 UTC, J7DevWeb commented on src/Service/AssociationService.php
> +    public function uploadImage(object $image, Associations $association)
Oui. Si je mets string ça me sort une erreur.
![image](https://user-images.githubusercontent.com/73040578/131327174-bb1324fb-1f44-4dea-bcd8-4fa9d2e76f28.png)

2021-08-30 10:52 UTC, J7DevWeb commented on templates/association/list.html.twig
> +        {{ association.email }}
La personnalisation du front est prévue dans un second temps. J'ai juste affiché les variables twig pour aider lors des tests. Lorsqu'Axentix sera ajouté au projet je personnaliserai le front si ça convient de procéder ainsi.

2021-08-30 11:17 UTC, gallarian requested changes

2021-08-30 11:17 UTC, gallarian commented on src/Service/AssociationService.php
> +    public function uploadImage(object $image, Associations $association)
c'est pas parce que y a un souci que l'on demande n'importe quoi? en php y a pas que le type string

2021-08-30 11:17 UTC, gallarian commented on templates/association/list.html.twig
> +        {{ association.email }}
non, je l'ai indiqué la derniere fois que c'etait un peu pauvre en balise HTML et ce pour toutes les vues concernées, c'est pas parce que le template sera fait plus tard qu'il faut pas faire un minimum de semantique de la page

2021-08-30 11:18 UTC, NouvelleTechno requested changes

2021-08-30 11:18 UTC, NouvelleTechno commented on src/Service/AssociationService.php
> +            unlink($this->params->get('association_images_directory'). '/' .$image);
Ca ne vérifie pas si le fichier existe vraiment

2021-08-31 15:05 UTC, gallarian requested changes

2021-08-31 15:05 UTC, gallarian commented on src/Controller/AssociationController.php
> +                $association->setPicture($uploadService->uploadImage($imageChange, 'association_images_directory'));
encore de la redondance dans les noms

2021-09-01 12:01 UTC, gallarian approved these changes

2021-09-03 16:54 UTC, NouvelleTechno approved these changes

2021-09-03 16:54 UTC, merged