Mise en place de la navbar pour le desktop, utilisation de layout pou…
Nouvelle-Techno-fr/JeBenevole.fr pull request #47
Opened 2021-09-03 14:46 UTC by Nox5

…r l'appelle des fichiers correspondant.

2021-09-03 15:08 UTC, gallarian requested changes

2021-09-03 15:08 UTC, gallarian commented on src/Controller/MainController.php
> +            'controller_name' => 'MainController',
a quoi sert la variable controller_name?

2021-09-03 15:08 UTC, gallarian commented on src/Controller/MainController.php
> +    }
a quoi sert cette methode? la methode index suffi pour avoir un rendu

2021-09-03 15:08 UTC, gallarian commented on templates/base.html.twig
>              {#{{ encore_entry_link_tags('app') }}#}
pourquoi garder du code qui ne servira pas? Encore n'est pas accepté pour ce projet

2021-09-03 15:08 UTC, gallarian commented on templates/main/index.html.twig
> +{% extends 'layout2.html.twig' %}
ou se trouve le fichier layout2.html.twig, je n'ai pas vu ce fichier

2021-09-03 15:08 UTC, gallarian commented on templates/layout.html.twig
> +{% endblock %}
pourquoi imbriquer le block navbar dans le block body alors que dans le fichier base, il y a pas cette imbrication et pourquoi un block pour la nav qui au final ne fait que une inclusion d'un autre fichier?

2021-09-03 15:08 UTC, gallarian commented on templates/partials/navbarNotLogged.html.twig
> +<!---NavbarUsersNotLoggedIn-->
pourquoi NavbarUsersNotLoggedIn? une autre navbar de prevue pour quand on est connecté?

2021-09-03 19:39 UTC, NouvelleTechno requested changes

2021-09-03 19:39 UTC, NouvelleTechno commented on templates/main/index.html.twig
> +{{ parent() }}
Pourquoi appeler parent ?

2021-09-03 22:22 UTC, gallarian commented on templates/main/index.html.twig
> +{{ parent() }}
Bien vu, je l'ai ratée celle-la mdr

2021-09-05 18:54 UTC, NouvelleTechno requested changes

2021-09-05 18:54 UTC, NouvelleTechno commented on templates/partials/footer/layout.html.twig
> +{% endblock %}
Pourquoi un extends et un bloc body sur un partial ? (idem sur navbar)

2021-11-07 13:41 UTC, NouvelleTechno commented
Bonjour, on en est ou de cette PR ?

2021-11-09 19:19 UTC, Thierry-Kq commented
> Bonjour, on en est ou de cette PR ?

Bonsoir, Nox a quitté le projet, je pense qu'on peut fermer cette PR.

2021-11-10 07:05 UTC, closed without merging