Better fixtures
Nouvelle-Techno-fr/JeBenevole.fr pull request #51
Opened 2021-09-05 02:34 UTC by Thierry-Kq

- [ ] Script added in composer for reload fixtures
- [ ] COMMANDS.md added
- [ ] faker added
- [ ] Better fixtures with relations

closes #48

2021-09-05 04:20 UTC, gallarian requested changes

2021-09-05 04:20 UTC, gallarian commented on composer.json
> +        "fzaninotto/faker": "^1.9",
this library is no longer up to date

2021-09-05 15:38 UTC, gallarian requested changes

2021-09-05 15:38 UTC, gallarian commented on composer.json
> -        "fzaninotto/faker": "^1.9",
why did you remove faker? 
I did not say to remove it but that it was no longer maintained

2021-09-05 17:38 UTC, Thierry-Kq commented on composer.json
> -        "fzaninotto/faker": "^1.9",
ok my bad, so i don't understand what i have to do here ?
Fix the version in composer? 
Btw, i saw i used composer require instead of composer require --dev, is that the problem?

2021-09-05 18:44 UTC, gallarian approved these changes

2021-09-05 19:01 UTC, NouvelleTechno commented
Why isn't faker used to generate addresses, cities... ?

2021-09-05 19:25 UTC, Thierry-Kq commented
> Why isn't faker used to generate addresses, cities... ?

First, i was updating fixtures to have some relations and to fix the parentId error in categoriesFixtures. 
Then, i used faker to have different kind of Users profils and get a better visibility on debug (with email, firstName and lastName).

For the moment, we don't realy use field like adress, phone etc, so i just let the old code for the moment, and i will improve them later when needed.

2021-09-09 05:45 UTC, NouvelleTechno approved these changes

2021-09-09 05:45 UTC, merged