Basic crud offers
Nouvelle-Techno-fr/JeBenevole.fr pull request #56
Opened 2021-09-12 00:06 UTC by Thierry-Kq

Basic CRUD for Offer / Request

For the moment, OfferController manage routes and actions for Offer and Request, should we split the Controller, or split few routes in the Controller? 

closes #28

2021-09-12 08:23 UTC, NouvelleTechno requested changes

2021-09-12 08:23 UTC, NouvelleTechno commented on src/Controller/OfferController.php
> +    public function show(Offers $offers): Response
Cette méthode ne vérifie pas le type d'offre. On aura du duplicate content

2021-09-12 08:23 UTC, NouvelleTechno commented on src/Entity/Offers.php
> +    private ?string $title;
Le titre est facultatif ? Vérifier aussi les autres propriétés

2021-09-12 08:23 UTC, NouvelleTechno commented on src/Form/OfferType.php
> +                    new File([
Contrainte Image ?

2021-09-12 20:53 UTC, Thierry-Kq commented on src/Entity/Offers.php
> +    private ?string $title;
En cas d'edit, si j'enlève la possibilité de null, et que j'enlève le required du formulaire, je récupère une 500 

Typed property App\Entity\Offers::$title must be string, null used

Fais comme ceci, je passe bien par la constraint du form @NotBlank 'Ce champ ne peut pas être vide.'

2021-09-12 20:57 UTC, Thierry-Kq commented on src/Form/OfferType.php
> +                    new File([
J'ai peut être manqué quelque chose, le champ 'file' n'est pas censé représenter une image?

2021-09-13 12:59 UTC, gallarian requested changes

2021-09-13 12:59 UTC, gallarian commented on src/Form/OfferType.php
> +                    new Length(['max' => 255])
pas de min? c'est une plateforme de mise en relation donc il faut du contenu serieux, genre la si je met "a" comme titre sa passe

2021-09-13 12:59 UTC, gallarian commented on src/Form/OfferType.php
> +                ]
pourquoi un type text alors que c'est prevu pour un email et pas de min non plus?

2021-09-13 12:59 UTC, gallarian commented on src/Form/OfferType.php
> +                    new Length(['max' => 255]),
pas de min?

2021-09-13 12:59 UTC, gallarian commented on src/Form/OfferType.php
> +                    new Length(['max' => 255])
pas de min?

2021-09-13 12:59 UTC, gallarian commented on src/Form/OfferType.php
> +                    new File([
file => fichier, Image => image
un fichier c'est vaste alors que image, c'est deja plus precis
voila le lien de la doc: https://symfony.com/doc/current/reference/constraints/Image.html

2021-09-13 12:59 UTC, gallarian commented on src/Controller/OfferController.php
> +
pas de gestion de la 410

2021-09-13 12:59 UTC, gallarian commented on src/Controller/OfferController.php
> +
pas de gestion de la 410

2021-09-13 12:59 UTC, gallarian commented on src/Controller/OfferController.php
> +
pas de gestion de la 410

2021-09-14 22:23 UTC, gallarian approved these changes

2021-09-18 19:50 UTC, Thierry-Kq commented on src/Entity/Offers.php
> +    private ?string $title;
Eventuellement passer par un DTO ?

2021-09-18 21:11 UTC, NouvelleTechno approved these changes

2021-09-18 21:11 UTC, merged