Crud categories
Nouvelle-Techno-fr/JeBenevole.fr pull request #62
Opened 2021-09-19 20:09 UTC by J7DevWeb

Basic CRUD for categories

This crud is made for admin.
When we delete a category with children, children became children of the father of the deleted category.

closes #49, closes #61

2021-09-19 20:32 UTC, gallarian requested changes

2021-09-19 20:32 UTC, gallarian commented on src/Form/CategoryType.php
> +                        'maxMessage' => 'max_length',
pourquoi une taille max pour un textarea? et surtout inférieur a un varchar

2021-09-20 06:17 UTC, J7DevWeb commented on src/Form/CategoryType.php
> +                        'maxMessage' => 'max_length',
En effet ce n'est pas logique. Je l'ai corrigé.

2021-09-22 03:02 UTC, gallarian approved these changes

2021-10-01 05:48 UTC, NouvelleTechno approved these changes

2021-10-01 05:49 UTC, merged