Register and login
Nouvelle-Techno-fr/JeBenevole.fr pull request #63
Opened 2021-09-30 00:53 UTC by Thierry-Kq

Login, Register and edit profile V1 done

---

**Register**

Required : 
- Email (email, notBlank)
- FirstName (notBlank, 2 - 60)
- LastName (notBlank, 2 - 60)
- Password (notBlank, 12 char, at least 1 uppercase and 1 lowercase, 1 number and 1 special char)
- Rgpd (accepted)

Send an email when register, auto login the user after registration, 1 hour to validate account (link in email) to set the Users.verified = true

---

**Login**
- Basic Login

---

**Edit profile**
- Description (15 - 3000)
- Picture (1024k)
- FixNumber (4 - 20)
- CellNumber (4 - 20)

---

**Small fixes**
- fix create/edit offer : if title already exist, deny the flush to not have a 500 (insert unique slug)

---

**Big thx to @J7DevWeb for the logo <3**

![screenshot-mailtrap io-2021 09 30-02_51_38](https://user-images.githubusercontent.com/17036413/135368012-f367bdc5-2790-4d2a-a2bb-5168eb1370e1.png)

closes #52, closes #26

2021-09-30 17:12 UTC, gallarian requested changes

2021-09-30 17:12 UTC, gallarian commented on src/Controller/ProfileController.php
> +            }
etape inutile, pour re-set l'ancienne image alors qu'elle est deja la, on a juste besoin de faire le set si l'utilisateur change d'image donc que $imageChange n'est pas null

2021-09-30 17:12 UTC, gallarian commented on src/Controller/ProfileController.php
> +            'user' => $user,
pas besoin de retourner le user etant donné que c'est le user co, donc recuperable directement dans twig

2021-10-01 06:00 UTC, NouvelleTechno requested changes

2021-10-07 09:49 UTC, merged