Axentix setup
Nouvelle-Techno-fr/JeBenevole.fr pull request #64
Opened 2021-09-30 20:35 UTC by J7DevWeb

Adding axentix.

2021-09-30 21:09 UTC, gallarian approved these changes

2021-10-01 06:01 UTC, NouvelleTechno requested changes

2021-10-01 06:01 UTC, NouvelleTechno commented on templates/base.html.twig
> +        <script src="{{ asset('assets/js/axentix.min.js') }}"></script>
Manque l'attribut defer stp

2021-10-01 19:39 UTC, J7DevWeb commented on templates/base.html.twig
> +        <script src="{{ asset('assets/js/axentix.min.js') }}"></script>
Correction faite.

2021-10-07 09:51 UTC, NouvelleTechno approved these changes

2021-10-07 09:51 UTC, merged