Non unique slug error on anonymized
Nouvelle-Techno-fr/JeBenevole.fr pull request #75
Opened 2021-11-06 19:18 UTC by Thierry-Kq

- Nickname added for Users, slug is now based on this nickname
- For Users / Asso / Offers / Categories, if slug already taken by a 410, deny the flush
- For Users and Asso, if email already taken, error message to not display "email already taken" message

closes #69, closes #58,  #70

2021-11-06 21:44 UTC, gallarian requested changes

2021-11-06 21:44 UTC, gallarian commented on src/Controller/Admin/CategoryController.php
>              $category = $form->getData();
l'assignation de $form->getData() ne sert a rien sur la variable $category car $category est deja hydraté

2021-11-06 21:44 UTC, gallarian commented on src/Controller/Admin/CategoryController.php
>              }
la modification ne sert a rien si aucune image n'a été soumise

2021-11-06 21:44 UTC, gallarian commented on src/Controller/AssociationController.php
>              $association = $form->getData();
l'assignation de $form->getData() ne sert a rien sur la variable $association car $association est deja hydraté

2021-11-06 21:44 UTC, gallarian commented on src/Entity/Users.php
> +    private ?string $nickname;
le nickname ne peut pas etre nullable

2021-11-06 21:44 UTC, gallarian commented on src/Entity/Users.php
> +    public function getNickname(): ?string
la methode ne peut pas retourner null

2021-11-07 13:48 UTC, NouvelleTechno requested changes

2021-11-07 13:48 UTC, NouvelleTechno commented on src/Controller/Admin/CategoryController.php
>          $em->flush();
Pourquoi ce flush sans try/catch ?

2021-11-09 19:14 UTC, Thierry-Kq commented on src/Controller/Admin/CategoryController.php
>              $category = $form->getData();
Bien vu, je corrige cette erreur et les suivantes similaires

2021-11-10 07:10 UTC, NouvelleTechno approved these changes

2021-11-11 19:52 UTC, gallarian approved these changes

2021-11-14 08:32 UTC, merged