AnonymizeService created
Nouvelle-Techno-fr/JeBenevole.fr pull request #77
Opened 2021-11-09 20:54 UTC by Thierry-Kq

A User can anonymize his profile.

closes #54

2021-11-10 07:29 UTC, NouvelleTechno commented
L'utilisateur ne devrait pas pouvoir anonymiser son compte directement, il devrait en faire la demande et un admin devrait le faire

2021-11-13 22:57 UTC, Thierry-Kq commented
> L'utilisateur ne devrait pas pouvoir anonymiser son compte directement, il devrait en faire la demande et un admin devrait le faire

Pas de soucis. L'utilisateur fais une demande avec un message (optionnel), et l'admin valide l'action pour anonymiser le compte, ce qui anonymize aussi ses Asso, ses Offers et ses Requests ?  Ou plutot juste un bouton qui envoie la demande a l'admin, et celui ci valide simplement la demande.

Par contre, un utilisateur peut sans passer par l'admin, anonymizer ses Requests/Offers/Associations c'est bien ça?

2021-11-14 08:36 UTC, NouvelleTechno requested changes

2021-11-14 08:36 UTC, NouvelleTechno commented on src/Controller/ProfileController.php
> +        if (u($request->server->get('HTTP_REFERER'))->containsAny('/profil/modification')) {
C'est quoi u ?

2021-11-14 08:36 UTC, NouvelleTechno commented on src/Controller/ProfileController.php
> +     * @Route("/profil/anonymisation", name="anonymize_profile")
Comment sait-on quel profil on anonymise ?

2021-11-16 19:15 UTC, Thierry-Kq commented on src/Controller/ProfileController.php
> +     * @Route("/profil/anonymisation", name="anonymize_profile")
C'etait pour anonymiser le profil du User connecté (son propre compte donc), mais ça n'a plus lieu d'être vu qu'un User doit faire la demande à un admin pour anonymiser son compte

2021-11-16 19:19 UTC, Thierry-Kq commented on src/Controller/ProfileController.php
> +        if (u($request->server->get('HTTP_REFERER'))->containsAny('/profil/modification')) {
C'est la fonction Symfony\Component\String\u (raccourci pour Symfony\Component\String\UnicodeString)

Je m'en sers pour comparer le referer avec l'url, pour vérifier que le User vient bien de cette Url, et qu'il n'a pas cliqué sur une url sans savoir ce que ça impliquerai pour lui. 

A enlever vu qu'un User ne peut pas anonymiser lui même son compte.

2022-03-30 17:59 UTC, closed without merging