Develop
Nouvelle-Techno-fr/JeBenevole.fr pull request #83
Opened 2022-02-26 19:58 UTC by Thierry-Kq

- Upgrade from 5.3 to 5.4
- Csrf added 
- JS validation for many forms
- Add a Service to keep anonymize logic 
- Few clean code with constants
- Contact page
- Messages flash added.
- Logos on navbar and sidebar fixed.
- Javascript validations added for the contact form.

2022-04-03 19:36 UTC, NouvelleTechno requested changes

2022-04-03 19:36 UTC, NouvelleTechno commented on .env
>  DATABASE_URL="postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=13&charset=utf8"
Pas MySQL ?

2022-04-03 19:36 UTC, NouvelleTechno commented on public/assets/js/validations/association.js
> +const form = document.getElementById('form');
Merci d'utiliser querySelector

2022-04-03 19:36 UTC, NouvelleTechno commented on public/assets/js/validations/association.js
> +    const mailformat = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Cette expression régulière a-t-elle été testée ?

2022-04-03 19:36 UTC, NouvelleTechno commented on src/Entity/Associations.php
> +     * @ORM\Column(type="string", length=100)
Une adresse ne peut pas dépasser 100 caractères ?

2022-04-03 19:36 UTC, NouvelleTechno commented on src/Service/UploadService.php
> +        $this->path = $this->params->get(self::DIRECTORY_FOLDER_NAME);
Pourquoi ne plus passer par le yaml ?

2022-04-14 17:37 UTC, Thierry-Kq commented on src/Service/UploadService.php
> +        $this->path = $this->params->get(self::DIRECTORY_FOLDER_NAME);
En fait on passe toujours par le yaml, c'est juste que la string 'images_directory' est définie dans la constante, si on doit s'en resservir, on ne risque plus de se tromper et c'est plus facile avec un editeur comme VScode ou PHPStorm pour trouver les références. 

En soit, ça ne change rien au code

2022-04-14 17:40 UTC, Thierry-Kq commented on src/Entity/Associations.php
> +     * @ORM\Column(type="string", length=100)
Il me semble que 100 c'est largement suffisant, par exemple, ceci fait 100 caractères exactement : 

`37 Boulevard Sainte Marie de la Mer, rue du père fouettard, avenue Garats
94312 Paris Cedex 07 France`

Sachant que la ville, le zip et le country sont des champs à part.

Si besoin je peux changer

2022-04-14 19:49 UTC, J7DevWeb commented on public/assets/js/validations/association.js
> +    const mailformat = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Je viens de la tester et cette Regex ne convient pas. Je vais la modifier.

2022-04-14 19:50 UTC, J7DevWeb commented on public/assets/js/validations/association.js
> +const form = document.getElementById('form');
Les changements seront effectués dans tous les fichiers js.

2022-04-14 19:52 UTC, J7DevWeb commented on .env
>  DATABASE_URL="postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=13&charset=utf8"
Nous n’utilisons pas ce fichier et par défaut la ligne est décommentée. Je vais la commenter pour l’instant.

2022-04-17 22:15 UTC, J7DevWeb commented on public/assets/js/validations/association.js
> +    const mailformat = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Le changement a été effectué dans la PR #104. On attend ton retour avant de merge.

2022-04-30 21:26 UTC, NouvelleTechno approved these changes

2022-04-30 21:27 UTC, merged